### PR TITLE
feat: updated hero image

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Update Hero image from figma

## Related Tickets & Documents
- Monday Task: https://blackberg-group.monday.com/boards/1931719392/pulses/7370392336

## QA Instructions, Screenshots, Recordings

Check new image in hero from figma: https://www.figma.com/design/YwFbJzXRBZeNr2OGWwSUEU/CCPI-Website?node-id=494-1146&node-type=FRAME&t=9HmGL5T3TQoVdeok-0

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _site/assets/img/home/hero-img.svg
 - assets/img/home/hero-img.svg

### CODE REVIEW

**Comment by RyanCrux** [comment]
Before: 
Screenshot 2024-09-05 at 10 43 44 AM

After:
Screenshot 2024-09-05 at 10 43 52 AM

**Comment by RyanCrux** [comment]
https://www.dev-innovation.bgsandbox.com/careandpayment/

**Review by will-bbg — CHANGES_REQUESTED** [review]
**Home page hero image**
- Reduce file size of image. Right now it is a whopping 8MB +

**Home page General**
- I missed this because I wasn't looking at Meta tags. However, the OG meta tags are empty. Please update those as they are key for their social media sharing. 
`
<meta property="og:title" content="((TITLE))">
<meta property="og:url" content="((URL))">
<meta property="og:description" content="((DESCRIPTION))">
<meta property="og:type" content="website">
<meta property="og:image" content="((OG:IMAGE URL))">
`

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
