### PR TITLE
CCPI - VETSmile development - 7179471038

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Creation of new page

## Related Tickets & Documents
- Monday Task: https://blackberg-group.monday.com/boards/1931719392/pulses/7179471038

## QA Instructions, Screenshots, Recordings

- Review/compare Figma layout
- "learn more" should smooth scroll to paragraph
- hero section is 100% height on all devices (adjusts dynamically) 

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _site/assets/img/vetsmile/calendar.png
 - _site/assets/img/vetsmile/chart-lines-2.png
 - _site/assets/img/vetsmile/chart-lines.png
 - _site/assets/img/vetsmile/heart.png
 - _site/assets/img/vetsmile/partners.png
 - _site/assets/img/vetsmile/tooth.png
 - assets/img/vetsmile/calendar.png
 - assets/img/vetsmile/chart-lines-2.png
 - assets/img/vetsmile/chart-lines.png
 - assets/img/vetsmile/heart.png
 - assets/img/vetsmile/partners.png
 - assets/img/vetsmile/tooth.png
 - _includes/header-sub.html
 - _includes/vetsmile/description.html
 - _includes/vetsmile/hero.html
 - _includes/vetsmile/stats.html
 - _site/assets/css/styles.css
 - _site/assets/sass/_uswds-theme-custom-styles.scss
 - _site/assets/sass/vha/pages/vetsmile/vs-description/_index.scss
 - _site/assets/sass/vha/pages/vetsmile/vs-hero/_index.scss
 - _site/assets/sass/vha/pages/vetsmile/vs-stats/_index.scss
 - _site/vetsmile/index.html
 - assets/css/styles.css
 - assets/sass/_uswds-theme-custom-styles.scss
 - assets/sass/vha/pages/vetsmile/vs-description/_index.scss
 - assets/sass/vha/pages/vetsmile/vs-hero/_index.scss
 - assets/sass/vha/pages/vetsmile/vs-stats/_index.scss
 - vetsmile/index.html

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
Screenshots below show issues. Left is Dev, right is Figma Mockup.

### Desktop

1. Hero content is not in a `.grid-container` and therefore does not align like it does in the mockup.
2. Font sizes do not match mockup.
3. Design element was exported out as a `.png` and is blurry on a retina screen. Export image as `.svg`.
Page 1

4. Design element does not have same placement as mockup.
Page 2

5. Font size does not match mockup.
6. Font size does not match mockup.
7. Design element was exported out as a `.png` and is blurry on a retina screen. Export image as `.svg`.
Page 3


### Tablet
8. Design element does not have same placement as mockup.
Page 4

9. Design element does not have same placement as mockup.
10. Font sizes do not match the mockup.
Page 5

### Mobile
11. Design element does not have same placement as mockup.
Page 6

12. Entire section does not match mobile mockup.
13. Font sizes do not match mockup.
Page 7

**Comment by RyanCrux** [comment]
1 Hero content is not in a .grid-container and therefore does not align like it does in the mockup.
DONE - rewrote to use grid-container

2 Font sizes do not match mockup.
DONE

3 Design element was exported out as a .png and is blurry on a retina screen. Export image as .svg.
DONE

4 Design element does not have same placement as mockup.
DONE

5 Font size does not match mockup.
DONE -  added font-sans-lg & text-light


6 Font size does not match mockup.
DONE

7 Design element was exported out as a .png and is blurry on a retina screen. Export image as .svg.
DONE

8 Design element does not have same placement as mockup.
DONE

9 Design element does not have same placement as mockup.
DONE

10 Font sizes do not match the mockup.
DONE

11 Design element does not have same placement as mockup.
DONE

12 Entire section does not match mobile mockup.
DONE

13 Font sizes do not match mockup.
DONE

**Review by will-bbg — CHANGES_REQUESTED** [review]
1. Hero container appears outside of the 12 column grid. Please review the mockup. The title and subtitle are to be aligned with the header nav and VHA title. 
Screenshot 2024-08-13 at 8 20 01 AM

Screenshot 2024-08-13 at 10 56 12 AM


2. On tablet and mobile, the text does not resize. Please review the mockup for proper font sizing. 
Screenshot 2024-08-13 at 8 22 23 AM

3. Hero design element still is not in the same position as in the mockup. The element is not supposed to be touching the bottom of the hero section. Please review mockup. The "reflection" element is supposed to overlap with the hero as seen in mockup.
Screenshot 2024-08-13 at 11 04 05 AM


4. Please use Heading tag for SEO.
Screenshot 2024-08-13 at 11 07 45 AM

5. On mobile, intro paragraph text does not resize. See mockup.

6. On mobile, Stat titles do not resize. See mockup.

7. The text, "For any questions related to the VETSmile program..." does not resize on mobile. See mockup

8. Hero background does not match mockup. 

Screenshot 2024-08-13 at 11 22 10 AM

**Review by will-bbg — APPROVED** [review]
👍🏽

**Pull request merged**
