### PR TITLE
Feat/jls 7209783224/ccpi about page development

### PR DESCRIPTION
**Pull request by ecstech-admin**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Development of newly designed CCPI About page

## Related Tickets & Documents
- Monday Task https://blackberg-group.monday.com/boards/1931719392/pulses/7209783224

## QA Instructions, Screenshots, Recordings
Review per Figma design: https://www.figma.com/design/YwFbJzXRBZeNr2OGWwSUEU/CCPI-Website?node-id=494-471&t=1C0EGei2RMxXIZU0-1

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _includes/about/alignment-fellowship.html
 - _includes/about/alignment-jim.html
 - _includes/about/alignment.html
 - _includes/about/establishment.html
 - _includes/about/page-title.html
 - _includes/home/flow.html
 - _includes/home/hero.html
 - _includes/home/pilot.html
 - _includes/our-team/page-title.html
 - _includes/our-team/team.html
 - _site/about/index.html
 - _site/assets/img/about/alignment-icon-medical-network.svg
 - _site/assets/img/about/alignment-icon-medical-team.svg
 - _site/assets/img/about/alignment-icon-personalized-hc.svg
 - _site/assets/img/about/alignment-icon-protection.svg
 - _site/assets/img/about/alignment-icon-us-flag.svg
 - _site/assets/img/home/1.svg
 - _site/assets/img/home/2.svg
 - _site/assets/img/home/3.svg
 - _site/assets/img/home/99.png
 - _site/assets/img/home/99.svg
 - _site/assets/img/home/bottom-arrow.svg
 - _site/assets/img/home/ccpi.svg
 - _site/assets/img/home/f-1.svg
 - _site/assets/img/home/f-2.svg
 - _site/assets/img/home/f-3.svg
 - _site/assets/img/home/f-4.svg
 - _site/assets/img/home/hero-glow.svg
 - _site/assets/img/home/hero-img.svg
 - _site/assets/img/home/top-arrow.svg
 - _site/assets/img/home/wdccpido.jpg
 - _site/assets/img/our-team/arrow.svg
 - _site/assets/img/our-team/bailee-b.png
 - _site/assets/img/our-team/david-a.png
 - _site/assets/img/our-team/deleena-s.png
 - _site/assets/img/our-team/donna-m.png
 - _site/assets/img/our-team/erin-g.png
 - _site/assets/img/our-team/hugh-w.png
 - _site/assets/img/our-team/joseph-w.png
 - _site/assets/img/our-team/kathryn-p.png
 - _site/assets/img/our-team/natalie-m.png
 - _site/assets/img/our-team/william-m.png
 - _site/assets/sass/vha/pages/about/_index.scss
 - _site/assets/sass/vha/pages/home/h-flow/_index.scss
 - _site/assets/sass/vha/pages/home/h-hero
 - copy/_index.scss
 - _site/assets/sass/vha/pages/home/h-hero/_index.scss
 - _site/assets/sass/vha/pages/home/h-pilot
 - copy/_index.scss
 - _site/assets/sass/vha/pages/home/h-pilot/_index.scss
 - _site/assets/sass/vha/pages/home/vs-hero/_index.scss
 - _site/assets/sass/vha/pages/our-team/_index.scss
 - _site/assets/uswds/img/usa-icons/navigate_next.svg
 - _site/our-team/index.html
 - about/index.html
 - assets/img/about/alignment-icon-medical-network.svg
 - assets/img/about/alignment-icon-medical-team.svg
 - assets/img/about/alignment-icon-personalized-hc.svg
 - assets/img/about/alignment-icon-protection.svg
 - assets/img/about/alignment-icon-us-flag.svg
 - assets/img/home/1.svg
 - assets/img/home/2.svg
 - assets/img/home/3.svg
 - assets/img/home/99.svg
 - assets/img/home/bottom-arrow.svg
 - assets/img/home/ccpi.svg
 - assets/img/home/f-1.svg
 - assets/img/home/f-2.svg
 - assets/img/home/f-3.svg
 - assets/img/home/f-4.svg
 - assets/img/home/hero-glow.svg
 - assets/img/home/hero-img.svg
 - assets/img/home/top-arrow.svg
 - assets/img/home/wdccpido.jpg
 - assets/img/our-team/arrow.svg
 - assets/img/our-team/bailee-b.png
 - assets/img/our-team/david-a.png
 - assets/img/our-team/deleena-s.png
 - assets/img/our-team/donna-m.png
 - assets/img/our-team/erin-g.png
 - assets/img/our-team/hugh-w.png
 - assets/img/our-team/joseph-w.png
 - assets/img/our-team/kathryn-p.png
 - assets/img/our-team/natalie-m.png
 - assets/img/our-team/william-m.png
 - assets/sass/vha/pages/about/_index.scss
 - assets/sass/vha/pages/home/h-flow/_index.scss
 - assets/sass/vha/pages/home/h-hero/_index.scss
 - assets/sass/vha/pages/home/h-pilot/_index.scss
 - assets/sass/vha/pages/our-team/_index.scss
 - assets/uswds/img/usa-icons/navigate_next.svg
 - our-team/index.html
 - _includes/header-sub.html
 - _includes/header.html
 - _site/assets/css/styles.css
 - _site/assets/sass/styles.scss
 - _site/assets/sass/vha/components/header/_index.scss
 - _site/assets/sass/vha/components/navigation/_index.scss
 - _site/assets/sass/vha/pages/_index.scss
 - _site/assets/sass/vha/pages/home/_index.scss
 - _site/index.html
 - _site/vetsmile/index.html
 - assets/.DS_Store
 - assets/css/styles.css
 - assets/sass/styles.scss
 - assets/sass/vha/components/header/_index.scss
 - assets/sass/vha/components/navigation/_index.scss
 - assets/sass/vha/pages/_index.scss
 - assets/sass/vha/pages/home/_index.scss
 - index.html

### CODE REVIEW

**Review by will-bbg — CHANGES_REQUESTED** [review]
1. "Home" breadcrumb goes to /oam
2. Change navigation label of the "About" page to "About CCPI"
3. Please adjust all navigation links so they only go to the directory rather than the index.html file. Example, "https://dev-innovation.bgsandbox.com/careandpayment/about/" rather than "https://dev-innovation.bgsandbox.com/careandpayment/about/index.html"
4. Double check layout of cards on tablet and mobile, bottom margin appears to be larger than mockup, image placement of last card is off as well.

**Comment by will-bbg** [comment]
@ecstech-admin I'm just now catching this but the page content needs to be wrapped in a <main> tag. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

**Comment by ecstech-admin** [comment]
1. Adjusted path to "Home" breadcrumb to go to careandpayment
2. Changed navigation label of the "About" page to "About CCPI"
3. Adjusted all navigation links to go to the directory rather than the index.html file.
4. Adjusted padding on cards to match Figma design
5. Wrapped page content in main tag

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request merged**
