### PR TITLE
Feat/rl 7209781370/home and our team page development ccpi

### PR DESCRIPTION
**Pull request by RyanCrux**
## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

New development of HOME page & OUR TEAM page

## Related Tickets & Documents
- Monday Task :
Home page: https://blackberg-group.monday.com/boards/1931719392/pulses/7209781370
Our Team: https://blackberg-group.monday.com/boards/1931719392/pulses/7209785401

## QA Instructions, Screenshots, Recordings

Figma: https://www.figma.com/design/YwFbJzXRBZeNr2OGWwSUEU/CCPI-Website?node-id=494-1841&t=aB6SyQx3UllwfVPl-0

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

## Changed Files in this Pull Request ##
- _includes/home/flow.html
 - _includes/home/hero.html
 - _includes/home/pilot.html
 - _includes/our-team/team.html
 - _site/assets/img/home/1.svg
 - _site/assets/img/home/2.svg
 - _site/assets/img/home/3.svg
 - _site/assets/img/home/99.svg
 - _site/assets/img/home/bottom-arrow.svg
 - _site/assets/img/home/ccpi.svg
 - _site/assets/img/home/f-1.svg
 - _site/assets/img/home/f-2.svg
 - _site/assets/img/home/f-3.svg
 - _site/assets/img/home/f-4.svg
 - _site/assets/img/home/hero-glow.svg
 - _site/assets/img/home/hero-img.svg
 - _site/assets/img/home/top-arrow.svg
 - _site/assets/img/home/wdccpido.jpg
 - _site/assets/img/our-team/arrow.svg
 - _site/assets/img/our-team/bailee-b.png
 - _site/assets/img/our-team/david-a.png
 - _site/assets/img/our-team/deleena-s.png
 - _site/assets/img/our-team/donna-m.png
 - _site/assets/img/our-team/erin-g.png
 - _site/assets/img/our-team/hugh-w.png
 - _site/assets/img/our-team/joseph-w.png
 - _site/assets/img/our-team/kathryn-p.png
 - _site/assets/img/our-team/natalie-m.png
 - _site/assets/img/our-team/william-m.png
 - _site/assets/sass/vha/pages/home/h-flow/_index.scss
 - _site/assets/sass/vha/pages/home/h-hero
 - copy/_index.scss
 - _site/assets/sass/vha/pages/home/h-hero/_index.scss
 - _site/assets/sass/vha/pages/home/h-pilot
 - copy/_index.scss
 - _site/assets/sass/vha/pages/home/h-pilot/_index.scss
 - _site/assets/sass/vha/pages/home/vs-hero/_index.scss
 - _site/assets/sass/vha/pages/our-team/_index.scss
 - _site/our-team/index.html
 - assets/img/home/1.svg
 - assets/img/home/2.svg
 - assets/img/home/3.svg
 - assets/img/home/99.svg
 - assets/img/home/bottom-arrow.svg
 - assets/img/home/ccpi.svg
 - assets/img/home/f-1.svg
 - assets/img/home/f-2.svg
 - assets/img/home/f-3.svg
 - assets/img/home/f-4.svg
 - assets/img/home/hero-glow.svg
 - assets/img/home/hero-img.svg
 - assets/img/home/top-arrow.svg
 - assets/img/home/wdccpido.jpg
 - assets/img/our-team/arrow.svg
 - assets/img/our-team/bailee-b.png
 - assets/img/our-team/david-a.png
 - assets/img/our-team/deleena-s.png
 - assets/img/our-team/donna-m.png
 - assets/img/our-team/erin-g.png
 - assets/img/our-team/hugh-w.png
 - assets/img/our-team/joseph-w.png
 - assets/img/our-team/kathryn-p.png
 - assets/img/our-team/natalie-m.png
 - assets/img/our-team/william-m.png
 - assets/sass/vha/pages/home/h-flow/_index.scss
 - assets/sass/vha/pages/home/h-hero/_index.scss
 - assets/sass/vha/pages/home/h-pilot/_index.scss
 - assets/sass/vha/pages/our-team/_index.scss
 - our-team/index.html
 - _site/assets/css/styles.css
 - _site/assets/sass/vha/pages/_index.scss
 - _site/assets/sass/vha/pages/home/_index.scss
 - _site/index.html
 - assets/.DS_Store
 - assets/css/styles.css
 - assets/sass/vha/pages/_index.scss
 - assets/sass/vha/pages/home/_index.scss
 - index.html

### CODE REVIEW

**Comment by RyanCrux** [comment]
Home page:
https://www.dev-innovation.bgsandbox.com/careandpayment/
Our Team page:
https://www.dev-innovation.bgsandbox.com/careandpayment/our-team/

**Comment by RyanCrux** [comment]
@will-bbg "What does CCPI do" section is on dev sandbox for review along with the rest of the homepage and our team page. 
Jim's About content is combined with this branch in a more recent PR.

**Review by will-bbg — CHANGES_REQUESTED** [review]
**Home Page**
1. Border radius on "Veteran-Centered, Value Driven" cards is too small.
2. Double check bottom padding of "Veteran-Centered, Value Driven". It doesn't appear to match the mockup.
3. Please adjust each content section to be wrapped in it's own <section> tag. Example of what I would prefer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#examples
4. CCPI's Waiver Authority, icon titles should be wrapped in a heading tag.
5. CCPI's Waiver Authority, like in the mockup, please make "Learn more" link to the about page. 

Both Pages
There is no <main> tag to wrap the contents of the site. Why is that? 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

**Comment by RyanCrux** [comment]
@will-bbg Requested changes have been made and available on dev for approval.

Home Page
Border radius on "Veteran-Centered, Value Driven" cards is too small.
DONE

Double check bottom padding of "Veteran-Centered, Value Driven". It doesn't appear to match the mockup.
DONE

Please adjust each content section to be wrapped in it's own tag. Example of what I would prefer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#examples
DONE

CCPI's Waiver Authority, icon titles should be wrapped in a heading tag.
DONE

CCPI's Waiver Authority, like in the mockup, please make "Learn more" link to the about page.
DONE

Both Pages
 There is no tag to wrap the contents of the site. 
DONE

**Review by will-bbg — APPROVED** [review]
🚀

**Pull request closed without merging**
